package com.example.contact
const val SHARED_CONTACT = "SHARED_CONTACT"
const val CONTACT_NAME = "CONTACT_NAME"
const val CONTACT_CHECKED_RB = "CONTACT_RB"
const val CONTACT_PHONE_EMAIL = "PHONE_EMAIL"
const val CONTACT_LIST = "CONTACT_LIST"
